sudo: required
services:
  - docker

before_install:
  - docker build -t bhaggi007/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run bhaggi007/react-test npm test -- -- coverage

after_success:
  - docker build -t bhaggi007/multi-client ./client
  - docker build -t bhaggi007/multi-nginx ./client
  - docker build -t bhaggi007/multi-server ./client
  - docker build -t bhaggi007/multi-worker ./client

# login to docker cli
- echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_ID" --password-stdin

# take images and push to docker hub
- docker push bhaggi007/multi-client
- docker push bhaggi007/multi-nginx
- docker push bhaggi007/multi-server
- docker push bhaggi007/multi-worker
